controllers:
    resource: ../src/Controller/
    type: attribute

main: 
    path: /main
    controller: App\Controller\MainController::index

accueil:
    path: /
    controller: App\Controller\MainController::accueil

afficher:
    path: /gestion_category/afficher
    controller: App\Controller\AdminCategoryController::category_afficher
